name: cleanup
on:
  schedule:
    - cron: "0 6 * * *" # every day at 6:00 AM

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old logs on the server
        uses: appleboy/ssh-action@25ce8cbbcb08177468c7ff7ec5cbfa236f9341e1 # v1.1.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          passphrase: ${{ secrets.DEPLOY_SSH_KEY_PASS }}
          script: |
            delete_excess_folders() {
                # Count the number of directories in the log folder
                NUM_DIRS=$(find "${{ secrets.DEPLOY_LOG_DIR }}" -mindepth 1 -maxdepth 1 -type d | wc -l)

                # Delete oldest directories until only 10 remain
                while [[ "$NUM_DIRS" -gt 9 ]]; do
                    OLDEST_DIR=$(find "${{ secrets.DEPLOY_LOG_DIR }}" -mindepth 1 -maxdepth 1 -type d -printf '%T+ %p\n' | sort | head -n 1 | cut -d" " -f2-)
                    if [[ -n "$OLDEST_DIR" ]]; then
                        echo "Deleting oldest directory: $OLDEST_DIR"
                        rm -rf "$OLDEST_DIR"
                        NUM_DIRS=$((NUM_DIRS - 1))
                    else
                        echo "No more directories to delete."
                        break
                    fi
                done
            }

            # Run the cleanup function
            delete_excess_folders

            # Generate a JSON file with the list of remaining directories
            TEMP_FILE=$(mktemp)
            find "${{ secrets.DEPLOY_LOG_DIR }}" -mindepth 1 -maxdepth 1 -type d -not -name 'lost+found' -exec basename {} \; | sort > "$TEMP_FILE"
            jq -R -s 'split("\n") | map(select(. != ""))' "$TEMP_FILE" > "${{ secrets.DEPLOY_LOG_DIR }}/logs.json"
            rm -f "$TEMP_FILE"
